name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check Go version
      run: go version


    # 2. Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.5

    # 3. Install dependencies
    - name: Install dependencies
      run: go mod tidy

    - name: Set environment variables from .env
      run: |
        if [ -f .env ]; then
        export $(cat .env | xargs)
        fi

    - name: Run tests
      env:
        OPENAI_API_KEY: "your_api_key"
        OPENAI_API_URL: "https://api.openai.com/v1/chat/completions"
      run: go test ./... -v


    # 4. Run tests and generate coverage report
    - name: Run tests with coverage
      run: go test ./... -coverprofile=coverage.out

    # 5. Upload coverage reports to Codecov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Codecov Token
        slug: cemtanrikut/go-openai-chatgpt-integration
        files: coverage.out                 # Coverage report file
        flags: unittests                    # Optional flag for distinguishing report types
